### PR TITLE
GDNative C++ bindings for Android

### PR DESCRIPTION
**Pull request by TGRCdev**
~~Work-in-progress, do not merge until all check boxes are ticked.~~

Ready for merge!

- [x] Working build script
- [x] Test platforms (`godot-cpp` build AND plugin build+run using [gdsqlite](https://github.com/khairul169/gdsqlite-native))
    - [x] Windows
        - [x] `godot-cpp` build
        - [x] Plugin build
        - [x] Plugin run
    - [x] Linux
        - [x] `godot-cpp` build
        - [x] Plugin build
        - [x] Plugin run
- [x] ~~Update README~~ Not really necessary
- [x] Final Rebase

Reference Material:
- https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md
- https://developer.android.com/ndk/guides/cpp-support

### CODE REVIEW

**Comment by Jayanth-L** [comment]
Sure :)

**Comment by TGRCdev** [comment]
@Jayanth-L, are you able to compile a working Android plugin with the latest CPP bindings? I have not been able to make a working plugin using the `master` branch of `godot-cpp` for Android no matter what I do, and I'm trying to figure out if it's an issue with `godot-cpp` or with my own configuration.

**Comment by Jayanth-L** [comment]
@TGRCdev

Sorry for late reply i was quite busy

I could compile arm64 binary with the SConstruct which i have  modified, it compiled successfully and tested on samsung device, can you let me know whats the error and which platform are you using (Linux or win/mac) ?

gdnative

**Comment by TGRCdev** [comment]
Thanks for the reply.

I'm compiling on Windows. I can compile, but any platform I run a plugin on gets to the Godot splash screen and never progresses past. It hangs and does not print anything to logcat after the first 3 startup lines.

I'm able to compile a working plugin with Nativescript 1.0 bindings, but Nativescript 1.1 bindings always cause a hang.

I will try to build using a Mac/Linux OS and see if I can find a fix from there.

**Comment by Jayanth-L** [comment]
> Thanks for the reply.
> 
> I'm compiling on Windows. I can compile, but any platform I run a plugin on gets to the Godot splash screen and never progresses past. It hangs and does not print anything to logcat after the first 3 startup lines.
> 
> I'm able to compile a working plugin with Nativescript 1.0 bindings, but Nativescript 1.1 bindings always cause a hang.
> 
> I will try to build using a Mac/Linux OS and see if I can find a fix from there.

Could you check if the library plugin is included in the armv8

**Comment by Jayanth-L** [comment]
Sorry i had accidentally closed pulled request, now opened :)

**Comment by TGRCdev** [comment]
@Jayanth-L I believe the branch is ready! I've tested it on Windows 10 and Lubuntu, and both builds run on my Samsung S10E.

My MacBook is old as hell and doesn't really work right, so I haven't gotten the chance to test it properly on OSX. However, it should work just the same.

Merge it whenever you're ready!

**Comment by Jayanth-L** [comment]
Sorry for the late reply

As this is your work and you have done the most of the work, I would suggest you to create a pull request on the main repository, and I will withdraw mine ;)

It's your decision, if you tell me to merge then I'll merge.

Very much thank you for your work ☺️

For now I'll merge ;)

**Pull request merged**
